import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('../src/client/ArkmeSettingsSurface.tsx', import.meta.url), 'utf8')
const shellSource = readFileSync(new URL('../src/client/ArkmePersistentShell.tsx', import.meta.url), 'utf8')
const navigationSource = readFileSync(new URL('../src/client/ArkmeProductNavigation.tsx', import.meta.url), 'utf8')
const adapterSource = readFileSync(new URL('../src/client/index.tsx', import.meta.url), 'utf8')
const redesignCss = readFileSync(new URL('../src/client/redesign/arkme-redesign.css', import.meta.url), 'utf8')

describe('ArkmeSettingsSurface', () => {
  it('keeps Arkme account capabilities separate from official application settings', () => {
    expect(source).toContain("callArkme<ArkmeUserProfileSnapshot>('user.profile'")
    expect(source).toContain("callArkme<ArkmeAuthSnapshot>('auth.logout')")
    expect(source).toContain('个人资料')
    expect(source).toContain('登录与安全')
    expect(source).toContain('退出登录')
    expect(source).toContain('aria-label="我的账户"')
    expect(source).not.toContain('模型与 API Key')
    expect(navigationSource).toContain('<strong>我的账户</strong>')
    expect(navigationSource).toContain('arkmeUi.openDshSettings()')
  })

  it('uses the Demo settings groups and adapts the DSH task conversation layout', () => {
    expect(redesignCss).toContain('.arkme-redesign-settings-group')
    expect(redesignCss).toContain('.arkme-redesign-settings-profile')
    expect(redesignCss).toContain('.arkme-redesign-task-conversation [data-chat-flow]')
    expect(redesignCss).toContain('--dsh-composer-card-max-width: calc(100% - 32px)')
    expect(redesignCss).toContain('--dsh-chat-content-width: calc(100% - 64px)')
    expect(redesignCss).toContain('max-width: none !important')
    expect(redesignCss).toContain('[data-arkme-directory-visible="true"]')
    expect(redesignCss).toContain('[data-arkme-directory-visible="false"]')
    expect(redesignCss).toContain('grid-template-columns: 356px minmax(0, 1fr) 0 !important')
    expect(redesignCss).toContain('grid-template-columns: 72px minmax(0, 1fr) 0 !important')
    expect(redesignCss).toContain('overflow-y: auto')
    expect(redesignCss).toContain('.arkme-redesign-profile-menu button')
    expect(redesignCss).toContain('background: transparent')
    expect(shellSource).toContain("authState.auth.status !== 'authenticated'")
    expect(shellSource).toContain("ui.calendarOpen !== true")
    expect(shellSource).not.toContain("renderSlot('sidebar.settings'")
    expect(adapterSource).toContain('arkmeUi.bindSettingsOpener(openOfficialSettings)')
    expect(adapterSource).toContain('[data-slot="sidebar.settings"] button[aria-haspopup="dialog"]')
    expect(adapterSource).toContain('[data-arkme-owned="persistent-sidebar"]')
    expect(adapterSource).not.toContain("document.querySelector<HTMLButtonElement>('button[aria-haspopup=\"dialog\"]')")
  })
})
